version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: tianjin/personage_blog
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:8000"
    networks:
      - webnet
    volumes:
      # Mount source-code for development
      - .:/personage_blog
networks:
  webnet: