# Generated by Django 2.1.7 on 2019-07-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
                ('put_date', models.DateTimeField(verbose_name='date published')),
                ('title_class', models.CharField(max_length=20)),
                ('text_type', models.CharField(max_length=20)),
                ('blog_type', models.CharField(max_length=20)),
                ('text_content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
