# Generated by Django 2.0 on 2019-07-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20190720_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_num',
            field=models.IntegerField(default=0),
        ),
    ]
